import fs from 'fs'
import path from 'path'

const stylesPath = path.resolve(__dirname, '../styles.css')

const N = 30

const commentForReplacement =
    '/* the following css has been generated by scripts/generate-styles */\n'

function main() {
    const styles = fs.readFileSync(stylesPath).toString()
    let generatedCss = commentForReplacement
    for (let index = 0; index < N; index++) {
        generatedCss += `.biafCascade > :nth-child(${index + 1}) {\n`
        generatedCss += `    --delay: calc(var(--initial-delay, 0ms) + ${index} * var(--increment));\n`
        generatedCss += `}\n`
    }
    const newStyles =
        styles.slice(0, styles.indexOf(commentForReplacement)) + generatedCss
    fs.writeFileSync(stylesPath, newStyles)
}

main()
